version: "3"

services:
    db:
        image: postgres
        container_name: db_api_reaction_news
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - ./data/db_data:/var/lib/postgresql/data

    # prisma:
    #     image: prismagraphql/prisma:1.34.9-gatsby
    #     container_name: prisma
    #     restart: always
    #     command: prisma migrate dev
    #     ports:
    #         - 4466:4466
    #     environment:
    #         DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    #     depends_on:
    #         - db

    api:
        build:
            context: .
        restart: always
        container_name: api_reaction_news
        command: prisma migrate dev
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: "5432"
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
        ports:
            - 3000:3000
        depends_on:
            - prisma
