version: "3.8"

services:
    db:
        image: postgres:14-alpine
        restart: always
        container_name: db_reaction_news
        environment:
            - POSTGRES_USER=neto
            - POSTGRESQL_PASSWORD=1234
            - POSTGRES_DB=db_reaction_news
        ports:
            - 5432:5432
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
